### ISSUE TITLE
Add link to GxEPD2/Add descriptors to Display Type dropdown

### ISSUE THREAD

**Issue by nullstalgia** [sidoh/epaper_templates#13]
So this was my first major hurdle once I got the software loaded onto the board. Currently, the dropdown list for the display types is just model numbers. And even looking on the linked Waveshare wiki to find my display (the default 4.2" B/W), I wasn't able to find any thing like that in the datasheet or manual!

I eventually opened up the GxEPD2 repo, and found the list of displays, and I was able to nail down which one was mine, which ended up being the default.

Personally, I'm okay with keeping the long model numbers there, but having either a link or a similar summary as the one on the GxEPD2 repo would be ideal.

![image](https://user-images.githubusercontent.com/20761757/77296067-3b16ae80-6ca4-11ea-936d-8dac3f9b6b52.png)

![image](https://user-images.githubusercontent.com/20761757/77296124-58e41380-6ca4-11ea-9c58-526314be2dcb.png)

I personally prefer the latter as it doesn't require going to another site, especially if outside internet connectivity is not possible at that moment.

**Comment by sidoh** [comment]
Makes sense, great idea.

Should be a way to serve it in the [`/api/v1/screens`](https://github.com/sidoh/epaper_templates/blob/master/lib/HTTP/EpaperWebServer.cpp#L584) route.  The list is in [DisplayTypeHelpers.cpp](https://github.com/sidoh/epaper_templates/blob/master/lib/Display/DisplayTypeHelpers.cpp).

**Comment by nullstalgia** [comment]
Closing due to pull #14 fixing this.
