### ISSUE TITLE
Bitmap dimensions that aren't divisible by 8 are not rendered correctly.

### ISSUE THREAD

**Issue by nullstalgia** [sidoh/epaper_templates#27]
20x20:

![image](https://user-images.githubusercontent.com/20761757/78422129-dfd4ac80-7611-11ea-8eaf-2e76f2b394ab.png)

32x32:

![image](https://user-images.githubusercontent.com/20761757/78422132-e5ca8d80-7611-11ea-85d7-03da65d058e6.png)

**Comment by sidoh** [comment]
Thanks, was able to reproduce on my end.

I think AdafruitGFX might be incapable of rendering bitmaps that don't have a width divisible by 8 ([see code](https://github.com/adafruit/Adafruit-GFX-Library/blob/master/Adafruit_GFX.cpp#L790)).  Having trouble thinking of a good reason for this (it's honestly a pretty goofy restriction), but that's how it is.

Confirmation: a 20x20 image doesn't work, but a 24x24 does.

As goofy as this feels, the best solution is probably just to re-implement `renderBitmap` in a way that supports arbitrary widths.  This isn't hard, and I don't quite understand why AdafruitGFX works the way it does.

**Comment by sidoh** [comment]
Should be fixed in #28.

**Comment by nullstalgia** [comment]
Will test very soon, thank you!

---

Unrelated, but are you going to close #5 since it has been solved?

**Comment by nullstalgia** [comment]
#28 does fix it.

But I have to ask, why are we able to change the width and height if doing anything but the actual size of the bitmap? Wouldn't it be best to set it from the given values in the Metadata? I'll write that out as and send it as a pull and you can see if you like it or not.

**Comment by sidoh** [comment]
Great, thanks for testing.

The bitmap metadata is relatively new, and was developed in the context of UI hinting.  The backend could definitely take advantage of the metadata in a way that it isn't right now.
