### ISSUE TITLE
Add option to select SPI CS pin

### ISSUE THREAD

**Issue by miroslavpetrov** [sidoh/epaper_templates#51]
I want to use the project with Adafruit E-paper feathering. In order to communicate to the e-paper display the CS pin should be defined. Since the featherwing is a good piece of hardware I think it would be good to add support for it in the project.

**Comment by sidoh** [comment]
Hey @miroslavpetrov,

either of the free SPI busses can be used (VSPI or HSPI). These are configurable in the settings menu.

VSPI has CS as 5, HSPI has CS as 15.

If you have a datasheet or a link to more detailed product information I can take a closer look.

**Comment by sidoh** [comment]
Added in v2.6.0.
