### ISSUE TITLE
Configurable NTP address

### ISSUE THREAD

**Issue by gardenali** [sidoh/epaper_templates#58]
I'd like to be able to change NTP server address without having to rebuild the image myself.
I have a device-only wifi network that doesn't have internet access (original intent was less noise on the wifi frequencies serving users, but these devices don't need internet access anyway)

**Comment by sidoh** [comment]
Reasonable request -- shouldn't be terribly hard to change. Happy to look at a PR, otherwise will try to get around to this when I can. :)

**Comment by sidoh** [comment]
Added in 2.6.0. Have a RC release here: https://github.com/sidoh/epaper_templates/releases/tag/v2.6.0-rc.1

**Comment by gardenali** [comment]
2.6.0-rc3 works nicely! Thanks a lot!
